# Generated by Django 5.2.9 on 2026-02-06 04:30

import InvenTree.fields
import InvenTree.models
import InvenTree.validators
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import generic.states.fields
import generic.states.states
import generic.states.transition
import generic.states.validators
import loan.status_codes
import loan.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0041_auto_20251203_1244'),
        ('company', '0077_delete_manufacturerpartparameter'),
        ('order', '0114_purchaseorderextraline_project_code_and_more'),
        ('part', '0146_auto_20251203_1241'),
        ('stock', '0116_alter_stockitem_link'),
        ('users', '0015_alter_userprofile_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('reference_int', models.BigIntegerField(default=0)),
                ('notes', InvenTree.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', max_length=50000, null=True, verbose_name='Notes')),
                ('barcode_data', models.CharField(blank=True, help_text='Third party barcode data', max_length=500, verbose_name='Barcode Data')),
                ('barcode_hash', models.CharField(blank=True, help_text='Unique hash of barcode data', max_length=128, verbose_name='Barcode Hash')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True)),
                ('total_price', InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Total price for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total Price')),
                ('order_currency', models.CharField(blank=True, help_text='Currency for this order (leave blank to use company default)', max_length=3, null=True, validators=[InvenTree.validators.validate_currency_code], verbose_name='Order Currency')),
                ('reference', models.CharField(default=loan.validators.generate_next_loan_order_reference, help_text='Loan order reference', max_length=64, unique=True, validators=[loan.validators.validate_loan_order_reference], verbose_name='Reference')),
                ('status', generic.states.fields.InvenTreeCustomStatusModelField(choices=[(10, 'Pending'), (20, 'Issued'), (25, 'On Hold'), (30, 'Returned'), (40, 'Converted to Sale'), (50, 'Cancelled'), (60, 'Written Off')], default=10, help_text='Loan order status', validators=[generic.states.validators.CustomStatusCodeValidator(status_class=loan.status_codes.LoanOrderStatus)], verbose_name='Status')),
                ('description', models.CharField(blank=True, help_text='Loan order description (optional)', max_length=250, verbose_name='Description')),
                ('link', InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external page', max_length=2000, verbose_name='Link')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('issue_date', models.DateField(blank=True, help_text='Date loan was issued', null=True, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, help_text='Expected return date for loaned items', null=True, verbose_name='Due Date')),
                ('return_date', models.DateField(blank=True, help_text='Actual date items were returned', null=True, verbose_name='Return Date')),
                ('address', models.ForeignKey(blank=True, help_text='Shipping address for loaned items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.address', verbose_name='Address')),
                ('borrower_company', models.ForeignKey(help_text='Company borrowing the items', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_orders', to='company.company', verbose_name='Borrower')),
                ('contact', models.ForeignKey(blank=True, help_text='Point of contact for this loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact')),
                ('converted_sales_order', models.ForeignKey(blank=True, help_text='Sales order created when loan was converted to sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_loan', to='order.salesorder', verbose_name='Converted Sales Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project_code', models.ForeignKey(blank=True, help_text='Select project code for this loan order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.projectcode', verbose_name='Project Code')),
                ('responsible', models.ForeignKey(blank=True, help_text='User or group responsible for this loan order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.owner', verbose_name='Responsible')),
            ],
            options={
                'verbose_name': 'Loan Order',
                'verbose_name_plural': 'Loan Orders',
            },
            bases=(generic.states.states.StatusCodeMixin, generic.states.transition.StateTransitionMixin, InvenTree.models.InvenTreeAttachmentMixin, InvenTree.models.InvenTreePermissionCheckMixin, InvenTree.models.ContentTypeMixin, InvenTree.models.PluginValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanOrderExtraLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=1, help_text='Quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('reference', models.CharField(blank=True, help_text='Line item reference', max_length=100, verbose_name='Reference')),
                ('description', models.CharField(blank=True, help_text='Description of the extra charge', max_length=250, verbose_name='Description')),
                ('notes', models.CharField(blank=True, help_text='Line item notes', max_length=500, verbose_name='Notes')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True)),
                ('price', InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Unit price', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price')),
                ('link', InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external page', max_length=2000, verbose_name='Link')),
                ('order', models.ForeignKey(help_text='Loan Order', on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='loan.loanorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Loan Order Extra Line',
                'verbose_name_plural': 'Loan Order Extra Lines',
            },
            bases=(InvenTree.models.ContentTypeMixin, InvenTree.models.PluginValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=1, help_text='Item quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('shipped', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=0, help_text='Quantity shipped out on loan', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shipped')),
                ('returned', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=0, help_text='Quantity returned from loan', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Returned')),
                ('status', generic.states.fields.InvenTreeCustomStatusModelField(choices=[(10, 'Pending'), (20, 'Shipped'), (30, 'Returned'), (40, 'Converted to Sale'), (45, 'Partially Converted'), (50, 'Lost'), (60, 'Damaged')], default=10, help_text='Line item status', validators=[generic.states.validators.CustomStatusCodeValidator(status_class=loan.status_codes.LoanOrderLineStatus)], verbose_name='Status')),
                ('loan_price_currency', djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True)),
                ('loan_price', InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Unit loan price (rental fee)', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Loan Price')),
                ('reference', models.CharField(blank=True, help_text='Line item reference', max_length=100, verbose_name='Reference')),
                ('notes', models.CharField(blank=True, help_text='Line item notes', max_length=500, verbose_name='Notes')),
                ('link', InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external page', max_length=2000, verbose_name='Link')),
                ('target_date', models.DateField(blank=True, help_text='Target return date for this line item', null=True, verbose_name='Target Date')),
                ('order', models.ForeignKey(help_text='Loan Order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='loan.loanorder', verbose_name='Order')),
                ('part', models.ForeignKey(help_text='Part', limit_choices_to={'salable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_order_line_items', to='part.part', verbose_name='Part')),
                ('project_code', models.ForeignKey(blank=True, help_text='Select project code for this line item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.projectcode', verbose_name='Project Code')),
            ],
            options={
                'verbose_name': 'Loan Order Line Item',
                'verbose_name_plural': 'Loan Order Line Items',
            },
            bases=(InvenTree.models.ContentTypeMixin, InvenTree.models.PluginValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanOrderAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=1, help_text='Enter stock allocation quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('returned', InvenTree.fields.RoundingDecimalField(decimal_places=5, default=0, help_text='Quantity returned from this allocation', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Returned')),
                ('item', models.ForeignKey(help_text='Select stock item to allocate', limit_choices_to={'belongs_to': None, 'part__salable': True, 'part__virtual': False, 'sales_order': None}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_order_allocations', to='stock.stockitem', verbose_name='Item')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='loan.loanorderlineitem', verbose_name='Line')),
            ],
            options={
                'verbose_name': 'Loan Order Allocation',
                'verbose_name_plural': 'Loan Order Allocations',
            },
        ),
    ]
