# Generated by Django 5.2.9 on 2026-02-06 05:00
# Note: status_custom_key columns are created by InvenTreeCustomStatusModelField.contribute_to_class()
# This migration syncs Django's state with the existing database columns.

import generic.states.fields
import generic.states.validators
import loan.status_codes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='loanorder',
                    name='status_custom_key',
                    field=generic.states.fields.ExtraInvenTreeCustomStatusModelField(
                        blank=True,
                        default=None,
                        help_text='Additional status information for this item',
                        null=True,
                        validators=[
                            generic.states.validators.CustomStatusCodeValidator(
                                status_class=loan.status_codes.LoanOrderStatus
                            ),
                        ],
                        verbose_name='Custom status key',
                    ),
                ),
                migrations.AddField(
                    model_name='loanorderlineitem',
                    name='status_custom_key',
                    field=generic.states.fields.ExtraInvenTreeCustomStatusModelField(
                        blank=True,
                        default=None,
                        help_text='Additional status information for this item',
                        null=True,
                        validators=[
                            generic.states.validators.CustomStatusCodeValidator(
                                status_class=loan.status_codes.LoanOrderLineStatus
                            ),
                        ],
                        verbose_name='Custom status key',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
