# Generated by Django 5.2.9 on 2026-02-10 00:50

import InvenTree.fields
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import generic.states.fields
import generic.states.validators
import loan.status_codes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_status_custom_key_noop'),
        ('order', '0114_purchaseorderextraline_project_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanorderallocation',
            name='converted_to_sales_allocation',
            field=models.ForeignKey(blank=True, help_text='Sales Order allocation this was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_loan_allocation', to='order.salesorderallocation', verbose_name='Converted to Sales Allocation'),
        ),
        migrations.AddField(
            model_name='loanorderallocation',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='Whether this allocation has been converted to sale', verbose_name='Is Converted'),
        ),
        migrations.AddField(
            model_name='loanorderlineitem',
            name='converted_date',
            field=models.DateTimeField(blank=True, help_text='Date when items were first converted to sale', null=True, verbose_name='Conversion Date'),
        ),
        migrations.AddField(
            model_name='loanorderlineitem',
            name='converted_quantity',
            field=InvenTree.fields.RoundingDecimalField(decimal_places=5, default=0, help_text='Total quantity converted to sale', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Converted Quantity'),
        ),
        migrations.AddField(
            model_name='loanorderlineitem',
            name='returned_and_sold_quantity',
            field=InvenTree.fields.RoundingDecimalField(decimal_places=5, default=0, help_text='Quantity that was returned from loan then sold separately', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Returned and Sold Quantity'),
        ),
        migrations.AlterField(
            model_name='loanorder',
            name='status',
            field=generic.states.fields.InvenTreeCustomStatusModelField(choices=[(10, 'Pending'), (15, 'Approved'), (20, 'Issued'), (25, 'On Hold'), (30, 'Returned'), (35, 'Partially Returned'), (40, 'Converted to Sale'), (50, 'Cancelled'), (60, 'Written Off')], default=10, help_text='Loan order status', validators=[generic.states.validators.CustomStatusCodeValidator(status_class=loan.status_codes.LoanOrderStatus)], verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LoanOrderLineConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, help_text='Quantity converted in this conversion', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('converted_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when conversion occurred', verbose_name='Conversion Date')),
                ('is_returned_items', models.BooleanField(default=False, help_text='Whether these items were returned from loan before conversion', verbose_name='Is Returned Items')),
                ('conversion_price_currency', djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True)),
                ('conversion_price', InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Unit price at which items were sold', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Conversion Price')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this conversion', verbose_name='Notes')),
                ('converted_by', models.ForeignKey(blank=True, help_text='User who performed the conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Converted By')),
                ('loan_line', models.ForeignKey(help_text='Loan order line item being converted', on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='loan.loanorderlineitem', verbose_name='Loan Line Item')),
                ('sales_order_line', models.ForeignKey(blank=True, help_text='Sales order line item created from this conversion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_from_loan', to='order.salesorderlineitem', verbose_name='Sales Order Line')),
            ],
            options={
                'verbose_name': 'Loan Order Line Conversion',
                'verbose_name_plural': 'Loan Order Line Conversions',
                'ordering': ['-converted_date'],
            },
        ),
    ]
