# Generated by Django 5.2.9 on 2026-02-15 05:39

import generic.states.fields
import generic.states.validators
import loan.status_codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanorderallocation_converted_to_sales_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanorder',
            name='ship_date',
            field=models.DateField(blank=True, help_text='Date items were shipped to borrower', null=True, verbose_name='Ship Date'),
        ),
        migrations.AlterField(
            model_name='loanorder',
            name='status',
            field=generic.states.fields.InvenTreeCustomStatusModelField(choices=[(10, 'Pending'), (15, 'Approved'), (20, 'Issued'), (22, 'Shipped'), (25, 'On Hold'), (30, 'Returned'), (35, 'Partially Returned'), (40, 'Converted to Sale'), (50, 'Cancelled'), (60, 'Written Off')], default=10, help_text='Loan order status', validators=[generic.states.validators.CustomStatusCodeValidator(status_class=loan.status_codes.LoanOrderStatus)], verbose_name='Status'),
        ),
    ]
